### ISSUE TITLE
Spelt dupe

### ISSUE THREAD

**Issue by aqualxx** [Globox1997/StuffZ#1]
When you have a spelt seed, no matter at what stage it grows, it will always drop itself and a piece of spelt. That means you can just spam right-click and left-click on a farmland and get infinite spelt and spelt seeds. Not very good for survival :P

Edit: It seemed to stop giving me spelt, but still giving me 2 spelt seeds

**Comment by Globox1997** [comment]
does this occur for all stuffz plants?

**Comment by Globox1997** [comment]
oh yeah I found something

**Comment by Globox1997** [comment]
fixed it.
thank you for your feedback, I appreciate it a lot ;)
