### ISSUE TITLE
Uncraft anvil bug (infinite materials)

### ISSUE THREAD

**Issue by varencilator** [Globox1997/StuffZ#3]
Can't put damaged tools on it (probably purposeful).
Removing tool from it by shift-rightclick gets tool back but leaves image of tool on uncraftanvil. Mining anvil will give only the anvil but hammering will still yield diamonds on anvil. Allows for infinite diamonds.
I'm using 1.16.5 with a lot of other mods (like carrier mod made me pick up anvil so I had to blacklist uncraftblock).

**Comment by Globox1997** [comment]
Yes damaged tools can't get uncrafted.
Should be fixed in version 2.3.0 with [https://github.com/Globox1997/StuffZ/commit/831b74ab7f1b100216fcfb585d8e1b4614d80925](https://github.com/Globox1997/StuffZ/commit/831b74ab7f1b100216fcfb585d8e1b4614d80925)
