### ISSUE TITLE
Cotton Sedds Problem

### ISSUE THREAD

**Issue by ClosedTheDor** [Globox1997/StuffZ#4]
Hey, i have a problem
when i play Minecraft the cottons seeds make me crash

**Comment by Globox1997** [comment]
please post here the crash log via a paste site

**Comment by ClosedTheDor** [comment]
Umm sorry this was another mod called "Cultivation" there were 2 cotton seeds and that was The cotton seeds of Cultivation that make me crash sorry again

**Comment by Globox1997** [comment]
no problem :)
