### ISSUE TITLE
[1.17] Possible mod conflict

### ISSUE THREAD

**Issue by kwpugh** [Globox1997/StuffZ#9]
Hi,

I'm kwpugh, author of Gobber.  Someone reported a crash when they used my teleport ring, which seems to not like the BrewingBarrel. 

He was teleporting away from the block, and it crashed.   Teleporting to it is fine.   Wondering if there is some kind of chunk loading situation.

Could you take a look at the attached issue and see if it makes sense to you?

Regards.

Kevin

https://github.com/kwpugh/gobber_fabric-1.17/issues/5

**Comment by kwpugh** [comment]
An update.  I noticed in my test world that if you teleport far away, I used /tp, outside the chunk where a barrel is cooking its ingredients, same crash.   I think it was discovered by using my Ring of Teleport, but even a /tp does it.

**Comment by kwpugh** [comment]
since no action here, I will close.

**Comment by Globox1997** [comment]
Hey kwpugh, 
sorry for not responding, I'm not maintaining this mod anymore

**Comment by kwpugh** [comment]
ok, good to know.  I won't worry  then.
